language: python
sudo: false
python:
  - "3.7"
  - "3.8"
  - "pypy3"
  - "nightly"
env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
matrix:
  allow_failures:
    - python: "pypy3"
    - env: DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox-travis
script: tox
