# Generated by Django 3.0.6 on 2020-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multifactorauth',
            old_name='sms_secret_key',
            new_name='secret_key',
        ),
        migrations.AlterField(
            model_name='multifactorauth',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'EMAIL'), ('', 'Off')], default='', max_length=16),
        ),
    ]
