name: Run linter and tests
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [2.2, 3.0, 3.1, 3.2, "master"]
        drf-version: [3.10, 3.11, 3.12, "master"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test-ci.txt
        pip install -r requirements/test.txt
    - name: Install Django
      run: |
        pip install "Django==${{ matrix.django-version }}.*"
    - name: Install DRF
      run: |
        pip install "djangorestframework==${{ matrix.drf-version }}.*"
    - name: Test
      run: |
        pytest --cov-report=xml
